"""Build COMPARISON.md from whatever result CSVs are present in results/.

Nothing here is hand-typed: every number in the report comes from the runs.
"""
from __future__ import annotations

import csv
import glob
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "common"))
import ravens  # noqa: E402

RESULTS = os.path.join(ROOT, "results")
PROBLEMS = ravens.load_all()
TRUTH = {p.name: p.answer for p in PROBLEMS}
SET_OF = {p.name: p.set_name for p in PROBLEMS}
ORDER = [p.name for p in PROBLEMS]


def read_csv(path):
    with open(path) as fh:
        return list(csv.DictReader(fh))


def load_runs():
    """[(label, {problem: answer}, extras)] in display order."""
    runs = []

    p = os.path.join(RESULTS, "original_answers.csv")
    if os.path.exists(p):
        ans = {r["RavensProblem"]: int(r["Agent's Answer"]) for r in read_csv(p)}
        runtime = None
        rt = os.path.join(RESULTS, "original_runtime.txt")
        if os.path.exists(rt):
            runtime = float(open(rt).read().strip())
        runs.append(("Original (2017)", ans, {"runtime": runtime, "kind": "original"}))

    p = os.path.join(RESULTS, "classical_answers.csv")
    if os.path.exists(p):
        rows = read_csv(p)
        summary = {}
        sp = os.path.join(RESULTS, "classical_summary.txt")
        if os.path.exists(sp):
            for line in open(sp):
                k, _, v = line.partition(":")
                summary[k.strip()] = v.strip()
        runs.append(("Classical AI (no training)",
                     {r["RavensProblem"]: int(r["AnswerNoTraining"]) for r in rows},
                     {"kind": "classical", "summary": summary}))
        runs.append(("Classical AI + learned ranker",
                     {r["RavensProblem"]: int(r["Answer"]) for r in rows},
                     {"kind": "classical",
                      "runtime": float(summary.get("runtime_seconds", 0) or 0),
                      "summary": summary}))

    for p in sorted(glob.glob(os.path.join(RESULTS, "llm_*_answers.csv"))):
        rows = read_csv(p)
        model = os.path.basename(p)[4:-12].replace("_", "-").replace("gpt-5-6", "gpt-5.6")
        wall = None
        sp = p.replace("_answers.csv", "_summary.txt")
        if os.path.exists(sp):
            for line in open(sp):
                if line.startswith("wall_seconds"):
                    wall = float(line.split(":")[1])
        extras = {
            "kind": "llm",
            "wall": wall,
            "runtime": sum(float(r["LatencySeconds"]) for r in rows),
            "in_tokens": sum(int(r["InputTokens"]) for r in rows),
            "out_tokens": sum(int(r["OutputTokens"]) for r in rows),
            "reasoning_tokens": sum(int(r["ReasoningTokens"]) for r in rows),
            "errors": sum(1 for r in rows if r["Error"]),
            "rules": {r["RavensProblem"]: r["Rule"] for r in rows},
        }
        runs.append((f"LLM: {model}",
                     {r["RavensProblem"]: int(r["Answer"]) for r in rows}, extras))
    return runs


def score(ans):
    correct = {n: (ans.get(n, -1) == TRUTH[n]) for n in ORDER}
    skipped = {n for n in ORDER if ans.get(n, -1) < 0}
    return correct, skipped


def pct(c, n):
    return f"{c}/{n} ({c/n:.0%})" if n else "-"


def main():
    runs = load_runs()
    scored = [(label, ans, extras, *score(ans)) for label, ans, extras in runs]
    n = len(ORDER)

    L = []
    w = L.append
    w("# Raven's Progressive Matrices: three generations of agent\n")
    w("All three agents are scored on the **same 96 problems** (Basic and Challenge "
      "sets B, C, D and E, 12 problems each) with the **same input** -- the panel "
      "images only. No agent is given the verbal representation that ships with "
      "sets Basic B and Basic C, because the other six sets do not have one.\n")
    w("Every number below is generated by `scripts/compare.py` from the CSVs in "
      "`results/`. Nothing is hand-entered.\n")

    # ---------- headline
    w("## Headline\n")
    w("| Agent | Correct | Accuracy | Skipped | Wall clock | Needs network |")
    w("|---|---|---|---|---|---|")
    for label, ans, ex, correct, skipped in scored:
        c = sum(correct.values())
        rt = ex.get("wall") or ex.get("runtime")
        rt_s = "-" if not rt else (f"{rt:.0f} s" if rt < 600 else f"{rt/60:.0f} min")
        w(f"| {label} | {c}/{n} | **{c/n:.1%}** | {len(skipped)} | {rt_s} | "
          f"{'yes' if ex.get('kind') == 'llm' else 'no'} |")
    w("")
    w("Chance is 13.5% (24 problems with 6 options, 72 with 8). Wall clock for the "
      "two local agents is single-process on a laptop; for the LLMs it is the "
      "whole 96-problem sweep at 10 concurrent requests.\n")

    # ---------- per set
    w("## By problem set\n")
    header = "| Agent | " + " | ".join(ravens.set_label(s) for s in ravens.SET_ORDER) + " | Total |"
    w(header)
    w("|" + "---|" * (len(ravens.SET_ORDER) + 2))
    for label, ans, ex, correct, skipped in scored:
        cells = []
        for s in ravens.SET_ORDER:
            names = [x for x in ORDER if SET_OF[x] == s]
            cells.append(str(sum(correct[x] for x in names)))
        w(f"| {label} | " + " | ".join(cells) + f" | **{sum(correct.values())}** |")
    w("")
    w("Twelve problems per set. `Basic B` and `Challenge B` are 2x2 matrices with "
      "six options; the rest are 3x3 with eight.\n")

    # ---------- agreement
    w("## Where they differ\n")
    main_runs = [(l, c) for l, a, e, c, s in scored
                 if l in ("Original (2017)", "Classical AI + learned ranker")
                 or l.startswith("LLM:")]
    if len(main_runs) >= 3:
        names_all_wrong = [x for x in ORDER if not any(c[x] for _, c in main_runs)]
        w(f"- **Nobody solved {len(names_all_wrong)}** of the 96: "
          + (", ".join(f"`{x}`" for x in names_all_wrong) if names_all_wrong else "none") + "\n")
        llm = next((c for l, c in main_runs if l.startswith("LLM:")), None)
        cls = next((c for l, c in main_runs if l.startswith("Classical")), None)
        org = next((c for l, c in main_runs if l.startswith("Original")), None)
        if llm and cls:
            only_llm = [x for x in ORDER if llm[x] and not cls[x]]
            only_cls = [x for x in ORDER if cls[x] and not llm[x]]
            w(f"- Solved by the LLM but not the classical agent: **{len(only_llm)}**")
            w(f"- Solved by the classical agent but not the LLM: **{len(only_cls)}**"
              + (" (" + ", ".join(f"`{x}`" for x in only_cls) + ")" if only_cls else ""))
        if org and cls:
            w(f"- Solved by the 2017 agent but not the classical agent: "
              f"**{len([x for x in ORDER if org[x] and not cls[x]])}**")
        w("")

    # ---------- cost
    llm_runs = [(l, e) for l, a, e, c, s in scored if e.get("kind") == "llm"]
    if llm_runs:
        w("## What the LLM runs cost\n")
        w("| Model | Accuracy | Input tokens | Output tokens | of which reasoning | "
          "Sum of per-call latency | API errors |")
        w("|---|---|---|---|---|---|---|")
        for label, ex in llm_runs:
            acc = next(sum(cc.values()) for l, a, e, cc, s in scored if l == label)
            w(f"| {label[5:]} | {acc}/{n} ({acc/n:.0%}) | {ex['in_tokens']:,} | "
              f"{ex['out_tokens']:,} | {ex['reasoning_tokens']:,} | "
              f"{ex['runtime']:.0f} s | {ex['errors']} |")
        w("")
        w("Runs used 10 concurrent workers, so wall-clock in the headline table is "
          "much lower than the summed latency here.\n")

    # ---------- per-problem appendix
    w("## Per-problem answers\n")
    w("`.` = correct, number = the wrong option it chose, `skip` = declined to answer.\n")
    labels = [l for l, *_ in scored]
    w("| Problem | Truth | " + " | ".join(labels) + " |")
    w("|" + "---|" * (len(labels) + 2))
    for x in ORDER:
        cells = []
        for label, ans, ex, correct, skipped in scored:
            a = ans.get(x, -1)
            cells.append("." if correct[x] else ("skip" if a < 0 else str(a)))
        w(f"| {x} | {TRUTH[x]} | " + " | ".join(cells) + " |")
    w("")

    out = os.path.join(ROOT, "COMPARISON.md")
    with open(out, "w") as fh:
        fh.write("\n".join(L))
    print(f"wrote {out} ({len(L)} lines)")

    # mirror the headline table into README.md between its markers
    readme = os.path.join(ROOT, "README.md")
    if os.path.exists(readme):
        head = L[L.index("## Headline"):L.index("## By problem set")]
        text = open(readme).read()
        a, b = "<!-- HEADLINE:START -->", "<!-- HEADLINE:END -->"
        if a in text and b in text:
            block = a + "\n" + "\n".join(head).replace("## Headline", "## Results") + b
            text = text[:text.index(a)] + block + text[text.index(b) + len(b):]
            open(readme, "w").write(text)
            print("updated README.md headline block")


if __name__ == "__main__":
    main()
