"""Extract what this build actually cost from the Claude Code session transcript.

Claude Code writes a JSONL transcript per session under
~/.claude/projects/<slugified-cwd>/<session-id>.jsonl, with a usage record on
every assistant turn. This reads it and writes results/session_stats.json so the
cost figures on the report are measured rather than estimated.

Usage:  python scripts/session_stats.py [path/to/transcript.jsonl]
"""
from __future__ import annotations

import collections
import datetime
import glob
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Files generated by other files here -- counted as output, not as authored code.
GENERATED = {"COMPARISON.md", "docs/index.html", "docs/accuracy.png"}
# Vendored 2017 sources -- not authored here.
VENDORED = ("01_original_2017/Agent.py", "01_original_2017/ProblemSet.py",
            "01_original_2017/Ravens", "01_original_2017/language.txt")


def find_transcript():
    slug = "-" + ROOT.replace("/", "-").lstrip("-")
    for base in glob.glob(os.path.expanduser("~/.claude/projects/*")):
        hits = glob.glob(os.path.join(base, "*.jsonl"))
        if hits and (slug.startswith(os.path.basename(base)) or
                     os.path.basename(base).startswith("-Users")):
            return max(hits, key=os.path.getmtime)
    return None


def read_transcript(path):
    usage = collections.Counter()
    tools = collections.Counter()
    turns = 0
    models = collections.Counter()
    stamps = []
    for line in open(path):
        try:
            rec = json.loads(line)
        except json.JSONDecodeError:
            continue
        if rec.get("timestamp"):
            stamps.append(rec["timestamp"])
        msg = rec.get("message") or {}
        u = msg.get("usage") or rec.get("usage")
        if u:
            turns += 1
            models[msg.get("model", "?")] += 1
            for k, v in u.items():
                if isinstance(v, int):
                    usage[k] += v
        if msg.get("role") == "assistant":
            for block in (msg.get("content") or []):
                if isinstance(block, dict) and block.get("type") == "tool_use":
                    tools[block["name"]] += 1
    span = None
    if stamps:
        fmt = lambda s: datetime.datetime.fromisoformat(s.replace("Z", "+00:00"))
        span = (fmt(max(stamps)) - fmt(min(stamps))).total_seconds()
    return dict(usage=dict(usage), tools=dict(tools), model_turns=turns,
                models=dict(models), span_seconds=span)


# Score lines the agents print, so the transcript can be turned into a timeline
# of when each capability actually existed.
MILESTONES = [
    (r"acc_all=([\d.]+)%", "2017 agent, all 96"),
    (r"TOTAL (\d+)/96", "non-LLM, rule vote only"),
    (r"\[A\] rule search only, no training : (\d+)/96", "non-LLM, no training"),
    (r"\[baseline\][^:]*: (\d+)/96", "non-LLM, no training"),
    (r"\[B\] rule search \+ learned ranker  : (\d+)/96", "non-LLM, learned (nested CV)"),
    (r"\[learned\] leave-one-SET-out[^:]*: (\d+)/96", "non-LLM, learned (CV)"),
    (r"^(gpt-[\w.-]+): (\d+)/96", "LLM full sweep"),
]


def timeline(path, tz_hours=-4):
    """When did each capability first exist? Times in the machine's local zone."""
    import re
    tz = datetime.timezone(datetime.timedelta(hours=tz_hours))
    out = []
    for line in open(path):
        try:
            rec = json.loads(line)
        except json.JSONDecodeError:
            continue
        ts = rec.get("timestamp")
        if not ts:
            continue
        when = datetime.datetime.fromisoformat(ts.replace("Z", "+00:00")).astimezone(tz)
        blob = json.dumps(rec.get("message", {}).get("content", ""))
        for pat, label in MILESTONES:
            for m in re.finditer(pat, blob, re.M):
                out.append((when.isoformat(timespec="seconds"), label, m.group(0)[:70]))
    out.sort()
    return out


def code_stats():
    files = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True,
                           text=True).stdout.split()
    buckets = collections.Counter()
    detail = {}
    for f in files:
        if f.startswith("Problems/") or f.startswith(VENDORED):
            continue
        path = os.path.join(ROOT, f)
        if not os.path.isfile(path):
            continue
        try:
            n = sum(1 for _ in open(path, encoding="utf-8"))
        except (UnicodeDecodeError, OSError):
            continue
        if f in GENERATED:
            key = "generated output"
        elif f.endswith(".py"):
            key = "python"
        elif f.endswith((".md", ".txt")) and not f.startswith("results/"):
            key = "prose"
        elif f.startswith("results/"):
            key = "results data"
        else:
            key = "config"
        buckets[key] += n
        detail[f] = [key, n]
    return {"by_kind": dict(buckets), "by_file": detail}


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else find_transcript()
    out = {"code": code_stats()}
    if path and os.path.exists(path):
        out["session"] = read_transcript(path)
        out["session"]["transcript"] = os.path.basename(path)
    else:
        print("no transcript found - writing code stats only", file=sys.stderr)

    if path and os.path.exists(path):
        tl = timeline(path)
        out["timeline"] = tl
        tpath = os.path.join(ROOT, "results", "session_timeline.txt")
        with open(tpath, "w") as fh:
            fh.write("when                        capability                     evidence\n")
            for when, label, ev in tl:
                fh.write(f"{when}  {label:28s}  {ev}\n")
        print(f"wrote {tpath}  ({len(tl)} milestones)")

    dest = os.path.join(ROOT, "results", "session_stats.json")
    with open(dest, "w") as fh:
        json.dump(out, fh, indent=2, sort_keys=True)
    print(json.dumps(out.get("session", {}), indent=2))
    print("code lines by kind:", json.dumps(out["code"]["by_kind"], indent=2))
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
